# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dc8ff7600d7af051597a2d704c265dd92db1ccd5f90064a76b0070b4ebbf77fd362b9898f8639f9c90e3e443005a4147a537a4a7910be1fc31c8e0bcd3e05013

test:
  secret_key_base: 4584a816da3542a96965b0a9e03bf1433b5fbdc2b8b23250ea74604a826bacf412171eeeae47ad73eed6212106237e5676ca7fb7132d2979ef7400506a76bae4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
